version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"

  # Maintain Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      go-dependencies:
        patterns:
          - "*"

  # Maintain Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(frontend)"
      include: "scope"
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  # Maintain Docs npm dependencies
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docs)"
      include: "scope"
    groups:
      docs-dependencies:
        patterns:
          - "*"
