// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';
import {options} from '../models';
import {context} from '../models';
import {app} from '../models';

export function CheckForUpdates():Promise<services.UpdateInfo>;

export function CheckSystemTools():Promise<models.SystemToolsReport>;

export function DetachWorkload(arg1:models.DetachConfig):Promise<void>;

export function DownloadAndInstallUpdate():Promise<void>;

export function GetAppSettings():Promise<models.AppSettings>;

export function GetKubeInfo(arg1:string):Promise<models.KubeInfo>;

export function InterceptWorkload(arg1:models.InterceptConfig):Promise<void>;

export function ListWorkloads():Promise<Array<models.Workload>>;

export function LoadConnectConfig():Promise<models.ConnectConfig>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function ReplaceWorkload(arg1:models.ReplaceConfig):Promise<void>;

export function ResetAppSettings():Promise<models.AppSettings>;

export function RestartApp():Promise<void>;

export function SaveAppSettings(arg1:models.AppSettings):Promise<void>;

export function SaveConnectConfig(arg1:models.ConnectConfig):Promise<void>;

export function SelectFile(arg1:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetEventEmitter(arg1:app.EventEmitter):Promise<void>;

export function SetNotifier(arg1:app.Notifier):Promise<void>;

export function StartTelepresence(arg1:models.ConnectConfig):Promise<void>;

export function StopTelepresence():Promise<void>;
