// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetachWorkload(arg1) {
  return window['go']['app']['App']['DetachWorkload'](arg1);
}

export function GetKubeInfo(arg1) {
  return window['go']['app']['App']['GetKubeInfo'](arg1);
}

export function InterceptWorkload(arg1) {
  return window['go']['app']['App']['InterceptWorkload'](arg1);
}

export function ListWorkloads() {
  return window['go']['app']['App']['ListWorkloads']();
}

export function LoadConnectConfig() {
  return window['go']['app']['App']['LoadConnectConfig']();
}

export function Notify(arg1, arg2) {
  return window['go']['app']['App']['Notify'](arg1, arg2);
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['app']['App']['OnSecondInstanceLaunch'](arg1);
}

export function SaveConnectConfig(arg1) {
  return window['go']['app']['App']['SaveConnectConfig'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['app']['App']['SelectFile'](arg1);
}

export function StartTelepresence(arg1) {
  return window['go']['app']['App']['StartTelepresence'](arg1);
}

export function StopTelepresence() {
  return window['go']['app']['App']['StopTelepresence']();
}
