// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListWorkloads() {
  return window['go']['main']['App']['ListWorkloads']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function StartTelepresence(arg1) {
  return window['go']['main']['App']['StartTelepresence'](arg1);
}

export function StopTelepresence() {
  return window['go']['main']['App']['StopTelepresence']();
}
