// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetKubeInfo():Promise<main.KubeInfo>;

export function ListWorkloads():Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function StartTelepresence(arg1:main.ConnectConfig):Promise<void>;

export function StopTelepresence():Promise<void>;
