// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DetachWorkload(arg1:main.DetachConfig):Promise<void>;

export function GetKubeInfo(arg1:string):Promise<main.KubeInfo>;

export function InterceptWorkload(arg1:main.InterceptConfig):Promise<void>;

export function ListWorkloads():Promise<Array<main.Workload>>;

export function LoadConnectConfig():Promise<main.ConnectConfig>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function SaveConnectConfig(arg1:main.ConnectConfig):Promise<void>;

export function SelectFile(arg1:string):Promise<string>;

export function StartTelepresence(arg1:main.ConnectConfig):Promise<void>;

export function StopTelepresence():Promise<void>;
