// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKubeInfo(arg1) {
  return window['go']['main']['App']['GetKubeInfo'](arg1);
}

export function InterceptWorkload(arg1) {
  return window['go']['main']['App']['InterceptWorkload'](arg1);
}

export function ListWorkloads() {
  return window['go']['main']['App']['ListWorkloads']();
}

export function LoadConnectConfig() {
  return window['go']['main']['App']['LoadConnectConfig']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function SaveConnectConfig(arg1) {
  return window['go']['main']['App']['SaveConnectConfig'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function StartTelepresence(arg1) {
  return window['go']['main']['App']['StartTelepresence'](arg1);
}

export function StopTelepresence() {
  return window['go']['main']['App']['StopTelepresence']();
}
